import z from "@/lib/zod";

export const clickEventSchemaTB = z.object({
  timestamp: z.string(),
  click_id: z.string(),
  link_id: z.string(),
  url: z.string(),
  country: z.string().nullish(),
  city: z.string().nullish(),
  region: z.string().nullish(),
  latitude: z.string().nullish(),
  longitude: z.string().nullish(),
  device: z.string().nullish(),
  device_model: z.string().nullish(),
  device_vendor: z.string().nullish(),
  browser: z.string().nullish(),
  browser_version: z.string().nullish(),
  os: z.string().nullish(),
  os_version: z.string().nullish(),
  engine: z.string().nullish(),
  engine_version: z.string().nullish(),
  cpu_architecture: z.string().nullish(),
  ua: z.string().nullish(),
  bot: z.number().nullish(),
  referer: z.string().nullish(),
  referer_url: z.string().nullish(),
  ip: z.string().nullish(),
  qr: z.number().nullish(),
});
