export const exampleData = {
  clicks: [
    {
      timestamp: "2024-06-09T16:12:02.556Z",
      click_id: "1",
      country: "US",
      city: "San Francisco",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "1",
        domain: "dub.link",
        key: "uxUrVCz",
        url: "https://dub.co/",
      },
    },
    {
      timestamp: "2024-06-09T15:52:02.556Z",
      click_id: "2",
      country: "US",
      city: "San Francisco",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "2",
        domain: "dub.link",
        key: "cHT2sg4",
        url: "https://google.com",
      },
    },
    {
      timestamp: "2024-06-08T13:32:02.556Z",
      click_id: "3",
      country: "US",
      city: "New York",
      device: "Desktop",
      browser: "Firefox",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "3",
        domain: "git.new",
        key: "9XyzIho",
        url: "https://github.com/dubinc/dub",
      },
    },
  ],
  leads: [
    {
      timestamp: "2024-06-11T17:03:56.000Z",
      event_id: "YbL8RwLTRRCxQz5H",
      event_name: "Sign up",
      country: "US",
      city: "San Francisco",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      ip: "",
      link: {
        id: "1",
        domain: "dub.link",
        key: "uxUrVCz",
        url: "https://dub.co/",
      },
      customer: {
        name: "Steven",
        email: "",
        avatar: "https://avatar.vercel.sh/s.png?text=S",
      },
    },
    {
      timestamp: "2024-06-10T16:07:56.000Z",
      event_id: "YbL8RwLTRRCxQz5H",
      event_name: "Sign up",
      country: "IN",
      city: "Kerala",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      ip: "",
      link: {
        id: "1",
        domain: "dub.link",
        key: "uxUrVCz",
        url: "https://dub.co/",
      },
      customer: {
        name: "Kiran",
        email: "",
        avatar: "https://avatar.vercel.sh/k.png?text=K",
      },
    },
    {
      timestamp: "2024-06-10T16:07:56.000Z",
      event_id: "YbL8RwLTRRCxQz5H",
      event_name: "Sign up",
      country: "US",
      city: "Pittsburgh",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      ip: "",
      link: {
        id: "1",
        domain: "dub.link",
        key: "uxUrVCz",
        url: "https://dub.co/",
      },
      customer: {
        name: "Tim",
        email: "",
        avatar: "https://avatar.vercel.sh/t.png?text=T",
      },
    },
  ],
  sales: [
    {
      timestamp: "2024-06-14T18:36:01.000Z",
      event_id: "Nffk2cwShKu5lQ7E",
      event_name: "Purchase",
      payment_processor: "stripe",
      invoice_id: "123456",
      amount: 900,
      country: "US",
      city: "San Francisco",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "clx97xeyl00017deqwbuvqmq7",
        domain: "dub.localhost",
        key: "0SHZh1V",
        url: "https://dub.co/",
      },
      customer: {
        name: "Steven",
        email: "",
        avatar: "https://avatar.vercel.sh/s.png?text=S",
      },
    },
    {
      timestamp: "2024-06-13T20:36:06.000Z",
      event_id: "Nffk2cwShKu5lQ7E",
      event_name: "Purchase",
      payment_processor: "stripe",
      invoice_id: "123456",
      amount: 700,
      country: "US",
      city: "Pittsburgh",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "clx97xeyl00017deqwbuvqmq7",
        domain: "dub.localhost",
        key: "0SHZh1V",
        url: "https://dub.co/",
      },
      customer: {
        name: "Tim",
        email: "",
        avatar: "https://avatar.vercel.sh/t.png?text=T",
      },
    },
    {
      timestamp: "2024-06-13T22:02:06.000Z",
      event_id: "Nffk2cwShKu5lQ7E",
      event_name: "Purchase",
      payment_processor: "stripe",
      invoice_id: "123456",
      amount: 1000,
      country: "IN",
      city: "Kerala",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      referer: "(direct)",
      qr: 0,
      link: {
        id: "clx97xeyl00017deqwbuvqmq7",
        domain: "dub.localhost",
        key: "0SHZh1V",
        url: "https://dub.co/",
      },
      customer: {
        name: "Kiran",
        email: "",
        avatar: "https://avatar.vercel.sh/k.png?text=K",
      },
    },
  ],
};
