import {
  Bolt,
  Calendar6,
  ChartLine,
  CirclePercentage,
  CursorRays,
  Flask,
  Folder,
  Gear3,
  Gift,
  Globe,
  Hyperlink,
  InvoiceDollar,
  License,
  MarketingTarget,
  MoneyBills2,
  Msgs,
  PaperPlane,
  Plug2,
  Receipt2,
  ShieldKeyhole,
  Shuffle,
  Sparkle3,
  SquareLayoutGrid5,
  UserCrown,
  UserFocus,
  Users2,
  UsersSettings,
  Versions2,
  Webhook,
} from "./nucleo";
import { Slack } from "./slack";

export const PLAN_FEATURE_ICONS = {
  clicks: CursorRays,
  links: Hyperlink,
  retention: Calendar6,
  sales: InvoiceDollar,
  domains: Globe,
  users: Users2,
  analytics: ChartLine,
  conversions: Receipt2,
  ai: Sparkle3,
  api: Plug2,
  advanced: Gear3,
  folders: Folder,
  dotlink: Gift,
  deeplinks: MarketingTarget,
  events: Bolt,
  webhooks: Webhook,
  roles: UsersSettings,
  slack: Slack,
  tests: Flask,
  email: PaperPlane,
  messages: Msgs,
  sso: ShieldKeyhole,
  logs: Versions2,
  success: UserCrown,
  sla: License,
  volume: CirclePercentage,

  clickpayouts: CursorRays,
  payouts: MoneyBills2,
  basicrewards: Gift,
  flexiblerewards: Shuffle,
  ailandingpage: Sparkle3,
  customerinsights: UserFocus,
  partners: Users2,
  embeddedreferrals: SquareLayoutGrid5,
};
