export const testIds = {
  auth: {
    signupSubmit: "auth-signup-submit",
    loginSubmit: "auth-login-submit",
    loginHeading: "auth-login-heading",
    verifyEmailHeading: "auth-verify-email-heading",
    loginNoAccount: "auth-login-no-account",
    loginInvalidCredentials: "auth-login-invalid-credentials",
  },
  onboarding: {
    getStarted: "onboarding-get-started",
    createWorkspace: "onboarding-create-workspace",
    workspaceName: "onboarding-workspace-name",
    workspaceSlug: "onboarding-workspace-slug",
    connectDomain: "onboarding-connect-domain",
    domainInput: "onboarding-domain-input",
    domainAvailable: "onboarding-domain-available",
    addDomain: "onboarding-add-domain",
    skipDomain: "onboarding-skip-domain",
    freePlan: "onboarding-free-plan",
    programCompanyName: "onboarding-program-company-name",
    programLogo: "onboarding-program-logo",
    programLogoUploaded: "onboarding-program-logo-uploaded",
    programDestinationUrl: "onboarding-program-destination-url",
    programSupportEmail: "onboarding-program-support-email",
    programContinue: "onboarding-program-continue",
    rewardAmount: "onboarding-reward-amount",
    rewardContinue: "onboarding-reward-continue",
    goToDashboard: "onboarding-go-to-dashboard",
    completeSetup: "onboarding-complete-setup",
    workspaceCreated: "onboarding-workspace-created",
    stepWelcome: "onboarding-step-welcome",
    stepWorkspace: "onboarding-step-workspace",
    stepProducts: "onboarding-step-products",
    stepDomain: "onboarding-step-domain",
    stepDomainCustom: "onboarding-step-domain-custom",
    stepProgram: "onboarding-step-program",
    stepReward: "onboarding-step-reward",
    stepPlan: "onboarding-step-plan",
    productCta: (product: "links" | "partners") =>
      `onboarding-product-cta-${product}` as const,
    planCta: (plan: string) =>
      `onboarding-plan-cta-${plan.toLowerCase()}` as const,
  },
  partnerOnboarding: {
    continue: "partner-onboarding-continue",
    skip: "partner-onboarding-skip",
    profile: "partner-onboarding-profile",
    platforms: "partner-onboarding-platforms",
    profileImage: "partner-onboarding-profile-image",
    aboutYou: "partner-onboarding-about-you",
    profileType: "partner-onboarding-profile-type",
  },
  billing: {
    plansHeading: "billing-plans-heading",
    viewDashboard: "billing-view-dashboard",
    upgradedHeading: "billing-upgraded-heading",
    startPaidPlan: "billing-start-paid-plan",
    viewPlans: "billing-view-plans",
    confirmStartPaidPlan: "billing-confirm-start-paid-plan",
    startPaidPlanHeading: "billing-start-paid-plan-heading",
    startPaidPlanNotice: "billing-start-paid-plan-notice",
    trialBanner: "billing-trial-banner",
    freeTrial: "billing-free-trial",
    planCta: (plan: string) =>
      `billing-plan-cta-${plan.toLowerCase()}` as const,
  },
} as const;
