import z from "@/lib/zod";

export const clickSchema = z.object({
  clickId: z.string(),
  aliasLinkId: z.string(),
  url: z.string(),
  ip: z.string(),
  continent: z.string(),
  country: z.string(),
  city: z.string(),
  region: z.string(),
  latitude: z.string(),
  longitude: z.string(),
  device: z.string(),
  deviceVendor: z.string(),
  deviceModel: z.string(),
  browser: z.string(),
  browserVersion: z.string(),
  engine: z.string(),
  engineVersion: z.string(),
  os: z.string(),
  osVersion: z.string(),
  cpuArchitecture: z.string(),
  ua: z.string(),
  bot: z.boolean(),
  qr: z.boolean(),
  referer: z.string(),
  refererUrl: z.string(),
  timestamp: z.string(),
  identityHash: z.string(),
  link: z.object({ id: z.string(), url: z.string() }),
});
