/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A short code indicating the error code returned.
 */
export enum FourHundredAndTwentyTwoCode {
    UnprocessableEntity = "unprocessable_entity",
}

export type FourHundredAndTwentyTwoError = {
    /**
     * A short code indicating the error code returned.
     */
    code: FourHundredAndTwentyTwoCode;
    /**
     * A human readable explanation of what went wrong.
     */
    message: string;
    /**
     * A link to our documentation with more details about this error code
     */
    docUrl?: string | undefined;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type FourHundredAndTwentyTwoData = {
    error: FourHundredAndTwentyTwoError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class FourHundredAndTwentyTwo extends Error {
    error: FourHundredAndTwentyTwoError;

    /** The original data that was passed to this error instance. */
    data$: FourHundredAndTwentyTwoData;

    constructor(err: FourHundredAndTwentyTwoData) {
        super("");
        this.data$ = err;

        this.error = err.error;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "FourHundredAndTwentyTwo";
    }
}

/** @internal */
export const FourHundredAndTwentyTwoCode$ = z.nativeEnum(FourHundredAndTwentyTwoCode);

/** @internal */
export namespace FourHundredAndTwentyTwoError$ {
    export type Inbound = {
        code: FourHundredAndTwentyTwoCode;
        message: string;
        doc_url?: string | undefined;
    };

    export const inboundSchema: z.ZodType<FourHundredAndTwentyTwoError, z.ZodTypeDef, Inbound> = z
        .object({
            code: FourHundredAndTwentyTwoCode$,
            message: z.string(),
            doc_url: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                message: v.message,
                ...(v.doc_url === undefined ? null : { docUrl: v.doc_url }),
            };
        });

    export type Outbound = {
        code: FourHundredAndTwentyTwoCode;
        message: string;
        doc_url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FourHundredAndTwentyTwoError> = z
        .object({
            code: FourHundredAndTwentyTwoCode$,
            message: z.string(),
            docUrl: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                message: v.message,
                ...(v.docUrl === undefined ? null : { doc_url: v.docUrl }),
            };
        });
}

/** @internal */
export namespace FourHundredAndTwentyTwo$ {
    export type Inbound = {
        error: FourHundredAndTwentyTwoError$.Inbound;
    };

    export const inboundSchema: z.ZodType<FourHundredAndTwentyTwo, z.ZodTypeDef, Inbound> = z
        .object({
            error: z.lazy(() => FourHundredAndTwentyTwoError$.inboundSchema),
        })
        .transform((v) => {
            return new FourHundredAndTwentyTwo({
                error: v.error,
            });
        });

    export type Outbound = {
        error: FourHundredAndTwentyTwoError$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FourHundredAndTwentyTwo> = z
        .instanceof(FourHundredAndTwentyTwo)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    error: z.lazy(() => FourHundredAndTwentyTwoError$.outboundSchema),
                })
                .transform((v) => {
                    return {
                        error: v.error,
                    };
                })
        );
}
