
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PartnerSalesChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PartnerSalesChannel
 * 
 */
export type PartnerSalesChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$PartnerSalesChannelPayload>

export type AggregatePartnerSalesChannel = {
  _count: PartnerSalesChannelCountAggregateOutputType | null
  _min: PartnerSalesChannelMinAggregateOutputType | null
  _max: PartnerSalesChannelMaxAggregateOutputType | null
}

export type PartnerSalesChannelMinAggregateOutputType = {
  partnerId: string | null
  salesChannel: $Enums.SalesChannel | null
}

export type PartnerSalesChannelMaxAggregateOutputType = {
  partnerId: string | null
  salesChannel: $Enums.SalesChannel | null
}

export type PartnerSalesChannelCountAggregateOutputType = {
  partnerId: number
  salesChannel: number
  _all: number
}


export type PartnerSalesChannelMinAggregateInputType = {
  partnerId?: true
  salesChannel?: true
}

export type PartnerSalesChannelMaxAggregateInputType = {
  partnerId?: true
  salesChannel?: true
}

export type PartnerSalesChannelCountAggregateInputType = {
  partnerId?: true
  salesChannel?: true
  _all?: true
}

export type PartnerSalesChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerSalesChannel to aggregate.
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerSalesChannels to fetch.
   */
  orderBy?: Prisma.PartnerSalesChannelOrderByWithRelationInput | Prisma.PartnerSalesChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PartnerSalesChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerSalesChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerSalesChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PartnerSalesChannels
  **/
  _count?: true | PartnerSalesChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PartnerSalesChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PartnerSalesChannelMaxAggregateInputType
}

export type GetPartnerSalesChannelAggregateType<T extends PartnerSalesChannelAggregateArgs> = {
      [P in keyof T & keyof AggregatePartnerSalesChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePartnerSalesChannel[P]>
    : Prisma.GetScalarType<T[P], AggregatePartnerSalesChannel[P]>
}




export type PartnerSalesChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartnerSalesChannelWhereInput
  orderBy?: Prisma.PartnerSalesChannelOrderByWithAggregationInput | Prisma.PartnerSalesChannelOrderByWithAggregationInput[]
  by: Prisma.PartnerSalesChannelScalarFieldEnum[] | Prisma.PartnerSalesChannelScalarFieldEnum
  having?: Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PartnerSalesChannelCountAggregateInputType | true
  _min?: PartnerSalesChannelMinAggregateInputType
  _max?: PartnerSalesChannelMaxAggregateInputType
}

export type PartnerSalesChannelGroupByOutputType = {
  partnerId: string
  salesChannel: $Enums.SalesChannel
  _count: PartnerSalesChannelCountAggregateOutputType | null
  _min: PartnerSalesChannelMinAggregateOutputType | null
  _max: PartnerSalesChannelMaxAggregateOutputType | null
}

type GetPartnerSalesChannelGroupByPayload<T extends PartnerSalesChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PartnerSalesChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PartnerSalesChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PartnerSalesChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PartnerSalesChannelGroupByOutputType[P]>
      }
    >
  >



export type PartnerSalesChannelWhereInput = {
  AND?: Prisma.PartnerSalesChannelWhereInput | Prisma.PartnerSalesChannelWhereInput[]
  OR?: Prisma.PartnerSalesChannelWhereInput[]
  NOT?: Prisma.PartnerSalesChannelWhereInput | Prisma.PartnerSalesChannelWhereInput[]
  partnerId?: Prisma.StringFilter<"PartnerSalesChannel"> | string
  salesChannel?: Prisma.EnumSalesChannelFilter<"PartnerSalesChannel"> | $Enums.SalesChannel
  partner?: Prisma.XOR<Prisma.PartnerScalarRelationFilter, Prisma.PartnerWhereInput>
}

export type PartnerSalesChannelOrderByWithRelationInput = {
  partnerId?: Prisma.SortOrder
  salesChannel?: Prisma.SortOrder
  partner?: Prisma.PartnerOrderByWithRelationInput
  _relevance?: Prisma.PartnerSalesChannelOrderByRelevanceInput
}

export type PartnerSalesChannelWhereUniqueInput = Prisma.AtLeast<{
  partnerId_salesChannel?: Prisma.PartnerSalesChannelPartnerIdSalesChannelCompoundUniqueInput
  AND?: Prisma.PartnerSalesChannelWhereInput | Prisma.PartnerSalesChannelWhereInput[]
  OR?: Prisma.PartnerSalesChannelWhereInput[]
  NOT?: Prisma.PartnerSalesChannelWhereInput | Prisma.PartnerSalesChannelWhereInput[]
  partnerId?: Prisma.StringFilter<"PartnerSalesChannel"> | string
  salesChannel?: Prisma.EnumSalesChannelFilter<"PartnerSalesChannel"> | $Enums.SalesChannel
  partner?: Prisma.XOR<Prisma.PartnerScalarRelationFilter, Prisma.PartnerWhereInput>
}, "partnerId_salesChannel">

export type PartnerSalesChannelOrderByWithAggregationInput = {
  partnerId?: Prisma.SortOrder
  salesChannel?: Prisma.SortOrder
  _count?: Prisma.PartnerSalesChannelCountOrderByAggregateInput
  _max?: Prisma.PartnerSalesChannelMaxOrderByAggregateInput
  _min?: Prisma.PartnerSalesChannelMinOrderByAggregateInput
}

export type PartnerSalesChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput | Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput | Prisma.PartnerSalesChannelScalarWhereWithAggregatesInput[]
  partnerId?: Prisma.StringWithAggregatesFilter<"PartnerSalesChannel"> | string
  salesChannel?: Prisma.EnumSalesChannelWithAggregatesFilter<"PartnerSalesChannel"> | $Enums.SalesChannel
}

export type PartnerSalesChannelCreateInput = {
  salesChannel: $Enums.SalesChannel
  partner: Prisma.PartnerCreateNestedOneWithoutSalesChannelsInput
}

export type PartnerSalesChannelUncheckedCreateInput = {
  partnerId: string
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelUpdateInput = {
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
  partner?: Prisma.PartnerUpdateOneRequiredWithoutSalesChannelsNestedInput
}

export type PartnerSalesChannelUncheckedUpdateInput = {
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}

export type PartnerSalesChannelCreateManyInput = {
  partnerId: string
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelUpdateManyMutationInput = {
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}

export type PartnerSalesChannelUncheckedUpdateManyInput = {
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}

export type PartnerSalesChannelListRelationFilter = {
  every?: Prisma.PartnerSalesChannelWhereInput
  some?: Prisma.PartnerSalesChannelWhereInput
  none?: Prisma.PartnerSalesChannelWhereInput
}

export type PartnerSalesChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PartnerSalesChannelOrderByRelevanceInput = {
  fields: Prisma.PartnerSalesChannelOrderByRelevanceFieldEnum | Prisma.PartnerSalesChannelOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PartnerSalesChannelPartnerIdSalesChannelCompoundUniqueInput = {
  partnerId: string
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelCountOrderByAggregateInput = {
  partnerId?: Prisma.SortOrder
  salesChannel?: Prisma.SortOrder
}

export type PartnerSalesChannelMaxOrderByAggregateInput = {
  partnerId?: Prisma.SortOrder
  salesChannel?: Prisma.SortOrder
}

export type PartnerSalesChannelMinOrderByAggregateInput = {
  partnerId?: Prisma.SortOrder
  salesChannel?: Prisma.SortOrder
}

export type PartnerSalesChannelCreateNestedManyWithoutPartnerInput = {
  create?: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput> | Prisma.PartnerSalesChannelCreateWithoutPartnerInput[] | Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput | Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput[]
  createMany?: Prisma.PartnerSalesChannelCreateManyPartnerInputEnvelope
  connect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
}

export type PartnerSalesChannelUncheckedCreateNestedManyWithoutPartnerInput = {
  create?: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput> | Prisma.PartnerSalesChannelCreateWithoutPartnerInput[] | Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput | Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput[]
  createMany?: Prisma.PartnerSalesChannelCreateManyPartnerInputEnvelope
  connect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
}

export type PartnerSalesChannelUpdateManyWithoutPartnerNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput> | Prisma.PartnerSalesChannelCreateWithoutPartnerInput[] | Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput | Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput[]
  upsert?: Prisma.PartnerSalesChannelUpsertWithWhereUniqueWithoutPartnerInput | Prisma.PartnerSalesChannelUpsertWithWhereUniqueWithoutPartnerInput[]
  createMany?: Prisma.PartnerSalesChannelCreateManyPartnerInputEnvelope
  set?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  disconnect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  delete?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  connect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  update?: Prisma.PartnerSalesChannelUpdateWithWhereUniqueWithoutPartnerInput | Prisma.PartnerSalesChannelUpdateWithWhereUniqueWithoutPartnerInput[]
  updateMany?: Prisma.PartnerSalesChannelUpdateManyWithWhereWithoutPartnerInput | Prisma.PartnerSalesChannelUpdateManyWithWhereWithoutPartnerInput[]
  deleteMany?: Prisma.PartnerSalesChannelScalarWhereInput | Prisma.PartnerSalesChannelScalarWhereInput[]
}

export type PartnerSalesChannelUncheckedUpdateManyWithoutPartnerNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput> | Prisma.PartnerSalesChannelCreateWithoutPartnerInput[] | Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput | Prisma.PartnerSalesChannelCreateOrConnectWithoutPartnerInput[]
  upsert?: Prisma.PartnerSalesChannelUpsertWithWhereUniqueWithoutPartnerInput | Prisma.PartnerSalesChannelUpsertWithWhereUniqueWithoutPartnerInput[]
  createMany?: Prisma.PartnerSalesChannelCreateManyPartnerInputEnvelope
  set?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  disconnect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  delete?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  connect?: Prisma.PartnerSalesChannelWhereUniqueInput | Prisma.PartnerSalesChannelWhereUniqueInput[]
  update?: Prisma.PartnerSalesChannelUpdateWithWhereUniqueWithoutPartnerInput | Prisma.PartnerSalesChannelUpdateWithWhereUniqueWithoutPartnerInput[]
  updateMany?: Prisma.PartnerSalesChannelUpdateManyWithWhereWithoutPartnerInput | Prisma.PartnerSalesChannelUpdateManyWithWhereWithoutPartnerInput[]
  deleteMany?: Prisma.PartnerSalesChannelScalarWhereInput | Prisma.PartnerSalesChannelScalarWhereInput[]
}

export type EnumSalesChannelFieldUpdateOperationsInput = {
  set?: $Enums.SalesChannel
}

export type PartnerSalesChannelCreateWithoutPartnerInput = {
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelUncheckedCreateWithoutPartnerInput = {
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelCreateOrConnectWithoutPartnerInput = {
  where: Prisma.PartnerSalesChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput>
}

export type PartnerSalesChannelCreateManyPartnerInputEnvelope = {
  data: Prisma.PartnerSalesChannelCreateManyPartnerInput | Prisma.PartnerSalesChannelCreateManyPartnerInput[]
  skipDuplicates?: boolean
}

export type PartnerSalesChannelUpsertWithWhereUniqueWithoutPartnerInput = {
  where: Prisma.PartnerSalesChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.PartnerSalesChannelUpdateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedUpdateWithoutPartnerInput>
  create: Prisma.XOR<Prisma.PartnerSalesChannelCreateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedCreateWithoutPartnerInput>
}

export type PartnerSalesChannelUpdateWithWhereUniqueWithoutPartnerInput = {
  where: Prisma.PartnerSalesChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.PartnerSalesChannelUpdateWithoutPartnerInput, Prisma.PartnerSalesChannelUncheckedUpdateWithoutPartnerInput>
}

export type PartnerSalesChannelUpdateManyWithWhereWithoutPartnerInput = {
  where: Prisma.PartnerSalesChannelScalarWhereInput
  data: Prisma.XOR<Prisma.PartnerSalesChannelUpdateManyMutationInput, Prisma.PartnerSalesChannelUncheckedUpdateManyWithoutPartnerInput>
}

export type PartnerSalesChannelScalarWhereInput = {
  AND?: Prisma.PartnerSalesChannelScalarWhereInput | Prisma.PartnerSalesChannelScalarWhereInput[]
  OR?: Prisma.PartnerSalesChannelScalarWhereInput[]
  NOT?: Prisma.PartnerSalesChannelScalarWhereInput | Prisma.PartnerSalesChannelScalarWhereInput[]
  partnerId?: Prisma.StringFilter<"PartnerSalesChannel"> | string
  salesChannel?: Prisma.EnumSalesChannelFilter<"PartnerSalesChannel"> | $Enums.SalesChannel
}

export type PartnerSalesChannelCreateManyPartnerInput = {
  salesChannel: $Enums.SalesChannel
}

export type PartnerSalesChannelUpdateWithoutPartnerInput = {
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}

export type PartnerSalesChannelUncheckedUpdateWithoutPartnerInput = {
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}

export type PartnerSalesChannelUncheckedUpdateManyWithoutPartnerInput = {
  salesChannel?: Prisma.EnumSalesChannelFieldUpdateOperationsInput | $Enums.SalesChannel
}



export type PartnerSalesChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  partnerId?: boolean
  salesChannel?: boolean
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerSalesChannel"]>



export type PartnerSalesChannelSelectScalar = {
  partnerId?: boolean
  salesChannel?: boolean
}

export type PartnerSalesChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"partnerId" | "salesChannel", ExtArgs["result"]["partnerSalesChannel"]>
export type PartnerSalesChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
}

export type $PartnerSalesChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PartnerSalesChannel"
  objects: {
    partner: Prisma.$PartnerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    partnerId: string
    salesChannel: $Enums.SalesChannel
  }, ExtArgs["result"]["partnerSalesChannel"]>
  composites: {}
}

export type PartnerSalesChannelGetPayload<S extends boolean | null | undefined | PartnerSalesChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload, S>

export type PartnerSalesChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PartnerSalesChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PartnerSalesChannelCountAggregateInputType | true
  }

export interface PartnerSalesChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PartnerSalesChannel'], meta: { name: 'PartnerSalesChannel' } }
  /**
   * Find zero or one PartnerSalesChannel that matches the filter.
   * @param {PartnerSalesChannelFindUniqueArgs} args - Arguments to find a PartnerSalesChannel
   * @example
   * // Get one PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PartnerSalesChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PartnerSalesChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PartnerSalesChannelFindUniqueOrThrowArgs} args - Arguments to find a PartnerSalesChannel
   * @example
   * // Get one PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PartnerSalesChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerSalesChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelFindFirstArgs} args - Arguments to find a PartnerSalesChannel
   * @example
   * // Get one PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PartnerSalesChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, PartnerSalesChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerSalesChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelFindFirstOrThrowArgs} args - Arguments to find a PartnerSalesChannel
   * @example
   * // Get one PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PartnerSalesChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PartnerSalesChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PartnerSalesChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PartnerSalesChannels
   * const partnerSalesChannels = await prisma.partnerSalesChannel.findMany()
   * 
   * // Get first 10 PartnerSalesChannels
   * const partnerSalesChannels = await prisma.partnerSalesChannel.findMany({ take: 10 })
   * 
   * // Only select the `partnerId`
   * const partnerSalesChannelWithPartnerIdOnly = await prisma.partnerSalesChannel.findMany({ select: { partnerId: true } })
   * 
   */
  findMany<T extends PartnerSalesChannelFindManyArgs>(args?: Prisma.SelectSubset<T, PartnerSalesChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PartnerSalesChannel.
   * @param {PartnerSalesChannelCreateArgs} args - Arguments to create a PartnerSalesChannel.
   * @example
   * // Create one PartnerSalesChannel
   * const PartnerSalesChannel = await prisma.partnerSalesChannel.create({
   *   data: {
   *     // ... data to create a PartnerSalesChannel
   *   }
   * })
   * 
   */
  create<T extends PartnerSalesChannelCreateArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelCreateArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PartnerSalesChannels.
   * @param {PartnerSalesChannelCreateManyArgs} args - Arguments to create many PartnerSalesChannels.
   * @example
   * // Create many PartnerSalesChannels
   * const partnerSalesChannel = await prisma.partnerSalesChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PartnerSalesChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, PartnerSalesChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PartnerSalesChannel.
   * @param {PartnerSalesChannelDeleteArgs} args - Arguments to delete one PartnerSalesChannel.
   * @example
   * // Delete one PartnerSalesChannel
   * const PartnerSalesChannel = await prisma.partnerSalesChannel.delete({
   *   where: {
   *     // ... filter to delete one PartnerSalesChannel
   *   }
   * })
   * 
   */
  delete<T extends PartnerSalesChannelDeleteArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PartnerSalesChannel.
   * @param {PartnerSalesChannelUpdateArgs} args - Arguments to update one PartnerSalesChannel.
   * @example
   * // Update one PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PartnerSalesChannelUpdateArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PartnerSalesChannels.
   * @param {PartnerSalesChannelDeleteManyArgs} args - Arguments to filter PartnerSalesChannels to delete.
   * @example
   * // Delete a few PartnerSalesChannels
   * const { count } = await prisma.partnerSalesChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PartnerSalesChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, PartnerSalesChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PartnerSalesChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PartnerSalesChannels
   * const partnerSalesChannel = await prisma.partnerSalesChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PartnerSalesChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PartnerSalesChannel.
   * @param {PartnerSalesChannelUpsertArgs} args - Arguments to update or create a PartnerSalesChannel.
   * @example
   * // Update or create a PartnerSalesChannel
   * const partnerSalesChannel = await prisma.partnerSalesChannel.upsert({
   *   create: {
   *     // ... data to create a PartnerSalesChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PartnerSalesChannel we want to update
   *   }
   * })
   */
  upsert<T extends PartnerSalesChannelUpsertArgs>(args: Prisma.SelectSubset<T, PartnerSalesChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__PartnerSalesChannelClient<runtime.Types.Result.GetResult<Prisma.$PartnerSalesChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PartnerSalesChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelCountArgs} args - Arguments to filter PartnerSalesChannels to count.
   * @example
   * // Count the number of PartnerSalesChannels
   * const count = await prisma.partnerSalesChannel.count({
   *   where: {
   *     // ... the filter for the PartnerSalesChannels we want to count
   *   }
   * })
  **/
  count<T extends PartnerSalesChannelCountArgs>(
    args?: Prisma.Subset<T, PartnerSalesChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PartnerSalesChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PartnerSalesChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PartnerSalesChannelAggregateArgs>(args: Prisma.Subset<T, PartnerSalesChannelAggregateArgs>): Prisma.PrismaPromise<GetPartnerSalesChannelAggregateType<T>>

  /**
   * Group by PartnerSalesChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerSalesChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PartnerSalesChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PartnerSalesChannelGroupByArgs['orderBy'] }
      : { orderBy?: PartnerSalesChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PartnerSalesChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPartnerSalesChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PartnerSalesChannel model
 */
readonly fields: PartnerSalesChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PartnerSalesChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PartnerSalesChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  partner<T extends Prisma.PartnerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PartnerDefaultArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PartnerSalesChannel model
 */
export interface PartnerSalesChannelFieldRefs {
  readonly partnerId: Prisma.FieldRef<"PartnerSalesChannel", 'String'>
  readonly salesChannel: Prisma.FieldRef<"PartnerSalesChannel", 'SalesChannel'>
}
    

// Custom InputTypes
/**
 * PartnerSalesChannel findUnique
 */
export type PartnerSalesChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter, which PartnerSalesChannel to fetch.
   */
  where: Prisma.PartnerSalesChannelWhereUniqueInput
}

/**
 * PartnerSalesChannel findUniqueOrThrow
 */
export type PartnerSalesChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter, which PartnerSalesChannel to fetch.
   */
  where: Prisma.PartnerSalesChannelWhereUniqueInput
}

/**
 * PartnerSalesChannel findFirst
 */
export type PartnerSalesChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter, which PartnerSalesChannel to fetch.
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerSalesChannels to fetch.
   */
  orderBy?: Prisma.PartnerSalesChannelOrderByWithRelationInput | Prisma.PartnerSalesChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerSalesChannels.
   */
  cursor?: Prisma.PartnerSalesChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerSalesChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerSalesChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerSalesChannels.
   */
  distinct?: Prisma.PartnerSalesChannelScalarFieldEnum | Prisma.PartnerSalesChannelScalarFieldEnum[]
}

/**
 * PartnerSalesChannel findFirstOrThrow
 */
export type PartnerSalesChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter, which PartnerSalesChannel to fetch.
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerSalesChannels to fetch.
   */
  orderBy?: Prisma.PartnerSalesChannelOrderByWithRelationInput | Prisma.PartnerSalesChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerSalesChannels.
   */
  cursor?: Prisma.PartnerSalesChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerSalesChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerSalesChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerSalesChannels.
   */
  distinct?: Prisma.PartnerSalesChannelScalarFieldEnum | Prisma.PartnerSalesChannelScalarFieldEnum[]
}

/**
 * PartnerSalesChannel findMany
 */
export type PartnerSalesChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter, which PartnerSalesChannels to fetch.
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerSalesChannels to fetch.
   */
  orderBy?: Prisma.PartnerSalesChannelOrderByWithRelationInput | Prisma.PartnerSalesChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PartnerSalesChannels.
   */
  cursor?: Prisma.PartnerSalesChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerSalesChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerSalesChannels.
   */
  skip?: number
  distinct?: Prisma.PartnerSalesChannelScalarFieldEnum | Prisma.PartnerSalesChannelScalarFieldEnum[]
}

/**
 * PartnerSalesChannel create
 */
export type PartnerSalesChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a PartnerSalesChannel.
   */
  data: Prisma.XOR<Prisma.PartnerSalesChannelCreateInput, Prisma.PartnerSalesChannelUncheckedCreateInput>
}

/**
 * PartnerSalesChannel createMany
 */
export type PartnerSalesChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PartnerSalesChannels.
   */
  data: Prisma.PartnerSalesChannelCreateManyInput | Prisma.PartnerSalesChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PartnerSalesChannel update
 */
export type PartnerSalesChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a PartnerSalesChannel.
   */
  data: Prisma.XOR<Prisma.PartnerSalesChannelUpdateInput, Prisma.PartnerSalesChannelUncheckedUpdateInput>
  /**
   * Choose, which PartnerSalesChannel to update.
   */
  where: Prisma.PartnerSalesChannelWhereUniqueInput
}

/**
 * PartnerSalesChannel updateMany
 */
export type PartnerSalesChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PartnerSalesChannels.
   */
  data: Prisma.XOR<Prisma.PartnerSalesChannelUpdateManyMutationInput, Prisma.PartnerSalesChannelUncheckedUpdateManyInput>
  /**
   * Filter which PartnerSalesChannels to update
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * Limit how many PartnerSalesChannels to update.
   */
  limit?: number
}

/**
 * PartnerSalesChannel upsert
 */
export type PartnerSalesChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the PartnerSalesChannel to update in case it exists.
   */
  where: Prisma.PartnerSalesChannelWhereUniqueInput
  /**
   * In case the PartnerSalesChannel found by the `where` argument doesn't exist, create a new PartnerSalesChannel with this data.
   */
  create: Prisma.XOR<Prisma.PartnerSalesChannelCreateInput, Prisma.PartnerSalesChannelUncheckedCreateInput>
  /**
   * In case the PartnerSalesChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PartnerSalesChannelUpdateInput, Prisma.PartnerSalesChannelUncheckedUpdateInput>
}

/**
 * PartnerSalesChannel delete
 */
export type PartnerSalesChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
  /**
   * Filter which PartnerSalesChannel to delete.
   */
  where: Prisma.PartnerSalesChannelWhereUniqueInput
}

/**
 * PartnerSalesChannel deleteMany
 */
export type PartnerSalesChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerSalesChannels to delete
   */
  where?: Prisma.PartnerSalesChannelWhereInput
  /**
   * Limit how many PartnerSalesChannels to delete.
   */
  limit?: number
}

/**
 * PartnerSalesChannel without action
 */
export type PartnerSalesChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerSalesChannel
   */
  select?: Prisma.PartnerSalesChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerSalesChannel
   */
  omit?: Prisma.PartnerSalesChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerSalesChannelInclude<ExtArgs> | null
}
