
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProgramCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProgramCategory
 * 
 */
export type ProgramCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ProgramCategoryPayload>

export type AggregateProgramCategory = {
  _count: ProgramCategoryCountAggregateOutputType | null
  _min: ProgramCategoryMinAggregateOutputType | null
  _max: ProgramCategoryMaxAggregateOutputType | null
}

export type ProgramCategoryMinAggregateOutputType = {
  programId: string | null
  category: $Enums.Category | null
}

export type ProgramCategoryMaxAggregateOutputType = {
  programId: string | null
  category: $Enums.Category | null
}

export type ProgramCategoryCountAggregateOutputType = {
  programId: number
  category: number
  _all: number
}


export type ProgramCategoryMinAggregateInputType = {
  programId?: true
  category?: true
}

export type ProgramCategoryMaxAggregateInputType = {
  programId?: true
  category?: true
}

export type ProgramCategoryCountAggregateInputType = {
  programId?: true
  category?: true
  _all?: true
}

export type ProgramCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramCategory to aggregate.
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramCategories to fetch.
   */
  orderBy?: Prisma.ProgramCategoryOrderByWithRelationInput | Prisma.ProgramCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProgramCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProgramCategories
  **/
  _count?: true | ProgramCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProgramCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProgramCategoryMaxAggregateInputType
}

export type GetProgramCategoryAggregateType<T extends ProgramCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateProgramCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProgramCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateProgramCategory[P]>
}




export type ProgramCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgramCategoryWhereInput
  orderBy?: Prisma.ProgramCategoryOrderByWithAggregationInput | Prisma.ProgramCategoryOrderByWithAggregationInput[]
  by: Prisma.ProgramCategoryScalarFieldEnum[] | Prisma.ProgramCategoryScalarFieldEnum
  having?: Prisma.ProgramCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProgramCategoryCountAggregateInputType | true
  _min?: ProgramCategoryMinAggregateInputType
  _max?: ProgramCategoryMaxAggregateInputType
}

export type ProgramCategoryGroupByOutputType = {
  programId: string
  category: $Enums.Category
  _count: ProgramCategoryCountAggregateOutputType | null
  _min: ProgramCategoryMinAggregateOutputType | null
  _max: ProgramCategoryMaxAggregateOutputType | null
}

type GetProgramCategoryGroupByPayload<T extends ProgramCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProgramCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProgramCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProgramCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProgramCategoryGroupByOutputType[P]>
      }
    >
  >



export type ProgramCategoryWhereInput = {
  AND?: Prisma.ProgramCategoryWhereInput | Prisma.ProgramCategoryWhereInput[]
  OR?: Prisma.ProgramCategoryWhereInput[]
  NOT?: Prisma.ProgramCategoryWhereInput | Prisma.ProgramCategoryWhereInput[]
  programId?: Prisma.StringFilter<"ProgramCategory"> | string
  category?: Prisma.EnumCategoryFilter<"ProgramCategory"> | $Enums.Category
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
}

export type ProgramCategoryOrderByWithRelationInput = {
  programId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  program?: Prisma.ProgramOrderByWithRelationInput
  _relevance?: Prisma.ProgramCategoryOrderByRelevanceInput
}

export type ProgramCategoryWhereUniqueInput = Prisma.AtLeast<{
  programId_category?: Prisma.ProgramCategoryProgramIdCategoryCompoundUniqueInput
  AND?: Prisma.ProgramCategoryWhereInput | Prisma.ProgramCategoryWhereInput[]
  OR?: Prisma.ProgramCategoryWhereInput[]
  NOT?: Prisma.ProgramCategoryWhereInput | Prisma.ProgramCategoryWhereInput[]
  programId?: Prisma.StringFilter<"ProgramCategory"> | string
  category?: Prisma.EnumCategoryFilter<"ProgramCategory"> | $Enums.Category
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
}, "programId_category">

export type ProgramCategoryOrderByWithAggregationInput = {
  programId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  _count?: Prisma.ProgramCategoryCountOrderByAggregateInput
  _max?: Prisma.ProgramCategoryMaxOrderByAggregateInput
  _min?: Prisma.ProgramCategoryMinOrderByAggregateInput
}

export type ProgramCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProgramCategoryScalarWhereWithAggregatesInput | Prisma.ProgramCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProgramCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProgramCategoryScalarWhereWithAggregatesInput | Prisma.ProgramCategoryScalarWhereWithAggregatesInput[]
  programId?: Prisma.StringWithAggregatesFilter<"ProgramCategory"> | string
  category?: Prisma.EnumCategoryWithAggregatesFilter<"ProgramCategory"> | $Enums.Category
}

export type ProgramCategoryCreateInput = {
  category: $Enums.Category
  program: Prisma.ProgramCreateNestedOneWithoutCategoriesInput
}

export type ProgramCategoryUncheckedCreateInput = {
  programId: string
  category: $Enums.Category
}

export type ProgramCategoryUpdateInput = {
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  program?: Prisma.ProgramUpdateOneRequiredWithoutCategoriesNestedInput
}

export type ProgramCategoryUncheckedUpdateInput = {
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}

export type ProgramCategoryCreateManyInput = {
  programId: string
  category: $Enums.Category
}

export type ProgramCategoryUpdateManyMutationInput = {
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}

export type ProgramCategoryUncheckedUpdateManyInput = {
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}

export type ProgramCategoryOrderByRelevanceInput = {
  fields: Prisma.ProgramCategoryOrderByRelevanceFieldEnum | Prisma.ProgramCategoryOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProgramCategoryProgramIdCategoryCompoundUniqueInput = {
  programId: string
  category: $Enums.Category
}

export type ProgramCategoryCountOrderByAggregateInput = {
  programId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProgramCategoryMaxOrderByAggregateInput = {
  programId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProgramCategoryMinOrderByAggregateInput = {
  programId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProgramCategoryListRelationFilter = {
  every?: Prisma.ProgramCategoryWhereInput
  some?: Prisma.ProgramCategoryWhereInput
  none?: Prisma.ProgramCategoryWhereInput
}

export type ProgramCategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumCategoryFieldUpdateOperationsInput = {
  set?: $Enums.Category
}

export type ProgramCategoryCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput> | Prisma.ProgramCategoryCreateWithoutProgramInput[] | Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput | Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.ProgramCategoryCreateManyProgramInputEnvelope
  connect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
}

export type ProgramCategoryUncheckedCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput> | Prisma.ProgramCategoryCreateWithoutProgramInput[] | Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput | Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.ProgramCategoryCreateManyProgramInputEnvelope
  connect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
}

export type ProgramCategoryUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput> | Prisma.ProgramCategoryCreateWithoutProgramInput[] | Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput | Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.ProgramCategoryUpsertWithWhereUniqueWithoutProgramInput | Prisma.ProgramCategoryUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.ProgramCategoryCreateManyProgramInputEnvelope
  set?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  disconnect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  delete?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  connect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  update?: Prisma.ProgramCategoryUpdateWithWhereUniqueWithoutProgramInput | Prisma.ProgramCategoryUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.ProgramCategoryUpdateManyWithWhereWithoutProgramInput | Prisma.ProgramCategoryUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.ProgramCategoryScalarWhereInput | Prisma.ProgramCategoryScalarWhereInput[]
}

export type ProgramCategoryUncheckedUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput> | Prisma.ProgramCategoryCreateWithoutProgramInput[] | Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput | Prisma.ProgramCategoryCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.ProgramCategoryUpsertWithWhereUniqueWithoutProgramInput | Prisma.ProgramCategoryUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.ProgramCategoryCreateManyProgramInputEnvelope
  set?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  disconnect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  delete?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  connect?: Prisma.ProgramCategoryWhereUniqueInput | Prisma.ProgramCategoryWhereUniqueInput[]
  update?: Prisma.ProgramCategoryUpdateWithWhereUniqueWithoutProgramInput | Prisma.ProgramCategoryUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.ProgramCategoryUpdateManyWithWhereWithoutProgramInput | Prisma.ProgramCategoryUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.ProgramCategoryScalarWhereInput | Prisma.ProgramCategoryScalarWhereInput[]
}

export type ProgramCategoryCreateWithoutProgramInput = {
  category: $Enums.Category
}

export type ProgramCategoryUncheckedCreateWithoutProgramInput = {
  category: $Enums.Category
}

export type ProgramCategoryCreateOrConnectWithoutProgramInput = {
  where: Prisma.ProgramCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput>
}

export type ProgramCategoryCreateManyProgramInputEnvelope = {
  data: Prisma.ProgramCategoryCreateManyProgramInput | Prisma.ProgramCategoryCreateManyProgramInput[]
  skipDuplicates?: boolean
}

export type ProgramCategoryUpsertWithWhereUniqueWithoutProgramInput = {
  where: Prisma.ProgramCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ProgramCategoryUpdateWithoutProgramInput, Prisma.ProgramCategoryUncheckedUpdateWithoutProgramInput>
  create: Prisma.XOR<Prisma.ProgramCategoryCreateWithoutProgramInput, Prisma.ProgramCategoryUncheckedCreateWithoutProgramInput>
}

export type ProgramCategoryUpdateWithWhereUniqueWithoutProgramInput = {
  where: Prisma.ProgramCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ProgramCategoryUpdateWithoutProgramInput, Prisma.ProgramCategoryUncheckedUpdateWithoutProgramInput>
}

export type ProgramCategoryUpdateManyWithWhereWithoutProgramInput = {
  where: Prisma.ProgramCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.ProgramCategoryUpdateManyMutationInput, Prisma.ProgramCategoryUncheckedUpdateManyWithoutProgramInput>
}

export type ProgramCategoryScalarWhereInput = {
  AND?: Prisma.ProgramCategoryScalarWhereInput | Prisma.ProgramCategoryScalarWhereInput[]
  OR?: Prisma.ProgramCategoryScalarWhereInput[]
  NOT?: Prisma.ProgramCategoryScalarWhereInput | Prisma.ProgramCategoryScalarWhereInput[]
  programId?: Prisma.StringFilter<"ProgramCategory"> | string
  category?: Prisma.EnumCategoryFilter<"ProgramCategory"> | $Enums.Category
}

export type ProgramCategoryCreateManyProgramInput = {
  category: $Enums.Category
}

export type ProgramCategoryUpdateWithoutProgramInput = {
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}

export type ProgramCategoryUncheckedUpdateWithoutProgramInput = {
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}

export type ProgramCategoryUncheckedUpdateManyWithoutProgramInput = {
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
}



export type ProgramCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  programId?: boolean
  category?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programCategory"]>



export type ProgramCategorySelectScalar = {
  programId?: boolean
  category?: boolean
}

export type ProgramCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"programId" | "category", ExtArgs["result"]["programCategory"]>
export type ProgramCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}

export type $ProgramCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProgramCategory"
  objects: {
    program: Prisma.$ProgramPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    programId: string
    category: $Enums.Category
  }, ExtArgs["result"]["programCategory"]>
  composites: {}
}

export type ProgramCategoryGetPayload<S extends boolean | null | undefined | ProgramCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload, S>

export type ProgramCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProgramCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProgramCategoryCountAggregateInputType | true
  }

export interface ProgramCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProgramCategory'], meta: { name: 'ProgramCategory' } }
  /**
   * Find zero or one ProgramCategory that matches the filter.
   * @param {ProgramCategoryFindUniqueArgs} args - Arguments to find a ProgramCategory
   * @example
   * // Get one ProgramCategory
   * const programCategory = await prisma.programCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProgramCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ProgramCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProgramCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProgramCategoryFindUniqueOrThrowArgs} args - Arguments to find a ProgramCategory
   * @example
   * // Get one ProgramCategory
   * const programCategory = await prisma.programCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProgramCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProgramCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryFindFirstArgs} args - Arguments to find a ProgramCategory
   * @example
   * // Get one ProgramCategory
   * const programCategory = await prisma.programCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProgramCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ProgramCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryFindFirstOrThrowArgs} args - Arguments to find a ProgramCategory
   * @example
   * // Get one ProgramCategory
   * const programCategory = await prisma.programCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProgramCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProgramCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProgramCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProgramCategories
   * const programCategories = await prisma.programCategory.findMany()
   * 
   * // Get first 10 ProgramCategories
   * const programCategories = await prisma.programCategory.findMany({ take: 10 })
   * 
   * // Only select the `programId`
   * const programCategoryWithProgramIdOnly = await prisma.programCategory.findMany({ select: { programId: true } })
   * 
   */
  findMany<T extends ProgramCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, ProgramCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProgramCategory.
   * @param {ProgramCategoryCreateArgs} args - Arguments to create a ProgramCategory.
   * @example
   * // Create one ProgramCategory
   * const ProgramCategory = await prisma.programCategory.create({
   *   data: {
   *     // ... data to create a ProgramCategory
   *   }
   * })
   * 
   */
  create<T extends ProgramCategoryCreateArgs>(args: Prisma.SelectSubset<T, ProgramCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProgramCategories.
   * @param {ProgramCategoryCreateManyArgs} args - Arguments to create many ProgramCategories.
   * @example
   * // Create many ProgramCategories
   * const programCategory = await prisma.programCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProgramCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ProgramCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ProgramCategory.
   * @param {ProgramCategoryDeleteArgs} args - Arguments to delete one ProgramCategory.
   * @example
   * // Delete one ProgramCategory
   * const ProgramCategory = await prisma.programCategory.delete({
   *   where: {
   *     // ... filter to delete one ProgramCategory
   *   }
   * })
   * 
   */
  delete<T extends ProgramCategoryDeleteArgs>(args: Prisma.SelectSubset<T, ProgramCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProgramCategory.
   * @param {ProgramCategoryUpdateArgs} args - Arguments to update one ProgramCategory.
   * @example
   * // Update one ProgramCategory
   * const programCategory = await prisma.programCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProgramCategoryUpdateArgs>(args: Prisma.SelectSubset<T, ProgramCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProgramCategories.
   * @param {ProgramCategoryDeleteManyArgs} args - Arguments to filter ProgramCategories to delete.
   * @example
   * // Delete a few ProgramCategories
   * const { count } = await prisma.programCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProgramCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProgramCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProgramCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProgramCategories
   * const programCategory = await prisma.programCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProgramCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ProgramCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ProgramCategory.
   * @param {ProgramCategoryUpsertArgs} args - Arguments to update or create a ProgramCategory.
   * @example
   * // Update or create a ProgramCategory
   * const programCategory = await prisma.programCategory.upsert({
   *   create: {
   *     // ... data to create a ProgramCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProgramCategory we want to update
   *   }
   * })
   */
  upsert<T extends ProgramCategoryUpsertArgs>(args: Prisma.SelectSubset<T, ProgramCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ProgramCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProgramCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProgramCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryCountArgs} args - Arguments to filter ProgramCategories to count.
   * @example
   * // Count the number of ProgramCategories
   * const count = await prisma.programCategory.count({
   *   where: {
   *     // ... the filter for the ProgramCategories we want to count
   *   }
   * })
  **/
  count<T extends ProgramCategoryCountArgs>(
    args?: Prisma.Subset<T, ProgramCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProgramCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProgramCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProgramCategoryAggregateArgs>(args: Prisma.Subset<T, ProgramCategoryAggregateArgs>): Prisma.PrismaPromise<GetProgramCategoryAggregateType<T>>

  /**
   * Group by ProgramCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProgramCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProgramCategoryGroupByArgs['orderBy'] }
      : { orderBy?: ProgramCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProgramCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProgramCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProgramCategory model
 */
readonly fields: ProgramCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProgramCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProgramCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  program<T extends Prisma.ProgramDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgramDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgramClient<runtime.Types.Result.GetResult<Prisma.$ProgramPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProgramCategory model
 */
export interface ProgramCategoryFieldRefs {
  readonly programId: Prisma.FieldRef<"ProgramCategory", 'String'>
  readonly category: Prisma.FieldRef<"ProgramCategory", 'Category'>
}
    

// Custom InputTypes
/**
 * ProgramCategory findUnique
 */
export type ProgramCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProgramCategory to fetch.
   */
  where: Prisma.ProgramCategoryWhereUniqueInput
}

/**
 * ProgramCategory findUniqueOrThrow
 */
export type ProgramCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProgramCategory to fetch.
   */
  where: Prisma.ProgramCategoryWhereUniqueInput
}

/**
 * ProgramCategory findFirst
 */
export type ProgramCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProgramCategory to fetch.
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramCategories to fetch.
   */
  orderBy?: Prisma.ProgramCategoryOrderByWithRelationInput | Prisma.ProgramCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramCategories.
   */
  cursor?: Prisma.ProgramCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramCategories.
   */
  distinct?: Prisma.ProgramCategoryScalarFieldEnum | Prisma.ProgramCategoryScalarFieldEnum[]
}

/**
 * ProgramCategory findFirstOrThrow
 */
export type ProgramCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProgramCategory to fetch.
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramCategories to fetch.
   */
  orderBy?: Prisma.ProgramCategoryOrderByWithRelationInput | Prisma.ProgramCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramCategories.
   */
  cursor?: Prisma.ProgramCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramCategories.
   */
  distinct?: Prisma.ProgramCategoryScalarFieldEnum | Prisma.ProgramCategoryScalarFieldEnum[]
}

/**
 * ProgramCategory findMany
 */
export type ProgramCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProgramCategories to fetch.
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramCategories to fetch.
   */
  orderBy?: Prisma.ProgramCategoryOrderByWithRelationInput | Prisma.ProgramCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProgramCategories.
   */
  cursor?: Prisma.ProgramCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramCategories.
   */
  skip?: number
  distinct?: Prisma.ProgramCategoryScalarFieldEnum | Prisma.ProgramCategoryScalarFieldEnum[]
}

/**
 * ProgramCategory create
 */
export type ProgramCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ProgramCategory.
   */
  data: Prisma.XOR<Prisma.ProgramCategoryCreateInput, Prisma.ProgramCategoryUncheckedCreateInput>
}

/**
 * ProgramCategory createMany
 */
export type ProgramCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProgramCategories.
   */
  data: Prisma.ProgramCategoryCreateManyInput | Prisma.ProgramCategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProgramCategory update
 */
export type ProgramCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ProgramCategory.
   */
  data: Prisma.XOR<Prisma.ProgramCategoryUpdateInput, Prisma.ProgramCategoryUncheckedUpdateInput>
  /**
   * Choose, which ProgramCategory to update.
   */
  where: Prisma.ProgramCategoryWhereUniqueInput
}

/**
 * ProgramCategory updateMany
 */
export type ProgramCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProgramCategories.
   */
  data: Prisma.XOR<Prisma.ProgramCategoryUpdateManyMutationInput, Prisma.ProgramCategoryUncheckedUpdateManyInput>
  /**
   * Filter which ProgramCategories to update
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * Limit how many ProgramCategories to update.
   */
  limit?: number
}

/**
 * ProgramCategory upsert
 */
export type ProgramCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ProgramCategory to update in case it exists.
   */
  where: Prisma.ProgramCategoryWhereUniqueInput
  /**
   * In case the ProgramCategory found by the `where` argument doesn't exist, create a new ProgramCategory with this data.
   */
  create: Prisma.XOR<Prisma.ProgramCategoryCreateInput, Prisma.ProgramCategoryUncheckedCreateInput>
  /**
   * In case the ProgramCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProgramCategoryUpdateInput, Prisma.ProgramCategoryUncheckedUpdateInput>
}

/**
 * ProgramCategory delete
 */
export type ProgramCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
  /**
   * Filter which ProgramCategory to delete.
   */
  where: Prisma.ProgramCategoryWhereUniqueInput
}

/**
 * ProgramCategory deleteMany
 */
export type ProgramCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramCategories to delete
   */
  where?: Prisma.ProgramCategoryWhereInput
  /**
   * Limit how many ProgramCategories to delete.
   */
  limit?: number
}

/**
 * ProgramCategory without action
 */
export type ProgramCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramCategory
   */
  select?: Prisma.ProgramCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramCategory
   */
  omit?: Prisma.ProgramCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramCategoryInclude<ExtArgs> | null
}
