
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SentEmail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SentEmail
 * 
 */
export type SentEmailModel = runtime.Types.Result.DefaultSelection<Prisma.$SentEmailPayload>

export type AggregateSentEmail = {
  _count: SentEmailCountAggregateOutputType | null
  _min: SentEmailMinAggregateOutputType | null
  _max: SentEmailMaxAggregateOutputType | null
}

export type SentEmailMinAggregateOutputType = {
  id: string | null
  type: string | null
  createdAt: Date | null
  projectId: string | null
}

export type SentEmailMaxAggregateOutputType = {
  id: string | null
  type: string | null
  createdAt: Date | null
  projectId: string | null
}

export type SentEmailCountAggregateOutputType = {
  id: number
  type: number
  createdAt: number
  projectId: number
  _all: number
}


export type SentEmailMinAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  projectId?: true
}

export type SentEmailMaxAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  projectId?: true
}

export type SentEmailCountAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  projectId?: true
  _all?: true
}

export type SentEmailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SentEmail to aggregate.
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SentEmails to fetch.
   */
  orderBy?: Prisma.SentEmailOrderByWithRelationInput | Prisma.SentEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SentEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SentEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SentEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SentEmails
  **/
  _count?: true | SentEmailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SentEmailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SentEmailMaxAggregateInputType
}

export type GetSentEmailAggregateType<T extends SentEmailAggregateArgs> = {
      [P in keyof T & keyof AggregateSentEmail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSentEmail[P]>
    : Prisma.GetScalarType<T[P], AggregateSentEmail[P]>
}




export type SentEmailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SentEmailWhereInput
  orderBy?: Prisma.SentEmailOrderByWithAggregationInput | Prisma.SentEmailOrderByWithAggregationInput[]
  by: Prisma.SentEmailScalarFieldEnum[] | Prisma.SentEmailScalarFieldEnum
  having?: Prisma.SentEmailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SentEmailCountAggregateInputType | true
  _min?: SentEmailMinAggregateInputType
  _max?: SentEmailMaxAggregateInputType
}

export type SentEmailGroupByOutputType = {
  id: string
  type: string
  createdAt: Date
  projectId: string | null
  _count: SentEmailCountAggregateOutputType | null
  _min: SentEmailMinAggregateOutputType | null
  _max: SentEmailMaxAggregateOutputType | null
}

type GetSentEmailGroupByPayload<T extends SentEmailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SentEmailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SentEmailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SentEmailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SentEmailGroupByOutputType[P]>
      }
    >
  >



export type SentEmailWhereInput = {
  AND?: Prisma.SentEmailWhereInput | Prisma.SentEmailWhereInput[]
  OR?: Prisma.SentEmailWhereInput[]
  NOT?: Prisma.SentEmailWhereInput | Prisma.SentEmailWhereInput[]
  id?: Prisma.StringFilter<"SentEmail"> | string
  type?: Prisma.StringFilter<"SentEmail"> | string
  createdAt?: Prisma.DateTimeFilter<"SentEmail"> | Date | string
  projectId?: Prisma.StringNullableFilter<"SentEmail"> | string | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
}

export type SentEmailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  _relevance?: Prisma.SentEmailOrderByRelevanceInput
}

export type SentEmailWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SentEmailWhereInput | Prisma.SentEmailWhereInput[]
  OR?: Prisma.SentEmailWhereInput[]
  NOT?: Prisma.SentEmailWhereInput | Prisma.SentEmailWhereInput[]
  type?: Prisma.StringFilter<"SentEmail"> | string
  createdAt?: Prisma.DateTimeFilter<"SentEmail"> | Date | string
  projectId?: Prisma.StringNullableFilter<"SentEmail"> | string | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
}, "id">

export type SentEmailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SentEmailCountOrderByAggregateInput
  _max?: Prisma.SentEmailMaxOrderByAggregateInput
  _min?: Prisma.SentEmailMinOrderByAggregateInput
}

export type SentEmailScalarWhereWithAggregatesInput = {
  AND?: Prisma.SentEmailScalarWhereWithAggregatesInput | Prisma.SentEmailScalarWhereWithAggregatesInput[]
  OR?: Prisma.SentEmailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SentEmailScalarWhereWithAggregatesInput | Prisma.SentEmailScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SentEmail"> | string
  type?: Prisma.StringWithAggregatesFilter<"SentEmail"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SentEmail"> | Date | string
  projectId?: Prisma.StringNullableWithAggregatesFilter<"SentEmail"> | string | null
}

export type SentEmailCreateInput = {
  id?: string
  type: string
  createdAt?: Date | string
  project?: Prisma.ProjectCreateNestedOneWithoutSentEmailsInput
}

export type SentEmailUncheckedCreateInput = {
  id?: string
  type: string
  createdAt?: Date | string
  projectId?: string | null
}

export type SentEmailUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneWithoutSentEmailsNestedInput
}

export type SentEmailUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SentEmailCreateManyInput = {
  id?: string
  type: string
  createdAt?: Date | string
  projectId?: string | null
}

export type SentEmailUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SentEmailUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SentEmailListRelationFilter = {
  every?: Prisma.SentEmailWhereInput
  some?: Prisma.SentEmailWhereInput
  none?: Prisma.SentEmailWhereInput
}

export type SentEmailOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SentEmailOrderByRelevanceInput = {
  fields: Prisma.SentEmailOrderByRelevanceFieldEnum | Prisma.SentEmailOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type SentEmailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type SentEmailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type SentEmailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type SentEmailCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput> | Prisma.SentEmailCreateWithoutProjectInput[] | Prisma.SentEmailUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.SentEmailCreateOrConnectWithoutProjectInput | Prisma.SentEmailCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.SentEmailCreateManyProjectInputEnvelope
  connect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
}

export type SentEmailUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput> | Prisma.SentEmailCreateWithoutProjectInput[] | Prisma.SentEmailUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.SentEmailCreateOrConnectWithoutProjectInput | Prisma.SentEmailCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.SentEmailCreateManyProjectInputEnvelope
  connect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
}

export type SentEmailUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput> | Prisma.SentEmailCreateWithoutProjectInput[] | Prisma.SentEmailUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.SentEmailCreateOrConnectWithoutProjectInput | Prisma.SentEmailCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.SentEmailUpsertWithWhereUniqueWithoutProjectInput | Prisma.SentEmailUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.SentEmailCreateManyProjectInputEnvelope
  set?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  disconnect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  delete?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  connect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  update?: Prisma.SentEmailUpdateWithWhereUniqueWithoutProjectInput | Prisma.SentEmailUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.SentEmailUpdateManyWithWhereWithoutProjectInput | Prisma.SentEmailUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.SentEmailScalarWhereInput | Prisma.SentEmailScalarWhereInput[]
}

export type SentEmailUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput> | Prisma.SentEmailCreateWithoutProjectInput[] | Prisma.SentEmailUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.SentEmailCreateOrConnectWithoutProjectInput | Prisma.SentEmailCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.SentEmailUpsertWithWhereUniqueWithoutProjectInput | Prisma.SentEmailUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.SentEmailCreateManyProjectInputEnvelope
  set?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  disconnect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  delete?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  connect?: Prisma.SentEmailWhereUniqueInput | Prisma.SentEmailWhereUniqueInput[]
  update?: Prisma.SentEmailUpdateWithWhereUniqueWithoutProjectInput | Prisma.SentEmailUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.SentEmailUpdateManyWithWhereWithoutProjectInput | Prisma.SentEmailUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.SentEmailScalarWhereInput | Prisma.SentEmailScalarWhereInput[]
}

export type SentEmailCreateWithoutProjectInput = {
  id?: string
  type: string
  createdAt?: Date | string
}

export type SentEmailUncheckedCreateWithoutProjectInput = {
  id?: string
  type: string
  createdAt?: Date | string
}

export type SentEmailCreateOrConnectWithoutProjectInput = {
  where: Prisma.SentEmailWhereUniqueInput
  create: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput>
}

export type SentEmailCreateManyProjectInputEnvelope = {
  data: Prisma.SentEmailCreateManyProjectInput | Prisma.SentEmailCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type SentEmailUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.SentEmailWhereUniqueInput
  update: Prisma.XOR<Prisma.SentEmailUpdateWithoutProjectInput, Prisma.SentEmailUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.SentEmailCreateWithoutProjectInput, Prisma.SentEmailUncheckedCreateWithoutProjectInput>
}

export type SentEmailUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.SentEmailWhereUniqueInput
  data: Prisma.XOR<Prisma.SentEmailUpdateWithoutProjectInput, Prisma.SentEmailUncheckedUpdateWithoutProjectInput>
}

export type SentEmailUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.SentEmailScalarWhereInput
  data: Prisma.XOR<Prisma.SentEmailUpdateManyMutationInput, Prisma.SentEmailUncheckedUpdateManyWithoutProjectInput>
}

export type SentEmailScalarWhereInput = {
  AND?: Prisma.SentEmailScalarWhereInput | Prisma.SentEmailScalarWhereInput[]
  OR?: Prisma.SentEmailScalarWhereInput[]
  NOT?: Prisma.SentEmailScalarWhereInput | Prisma.SentEmailScalarWhereInput[]
  id?: Prisma.StringFilter<"SentEmail"> | string
  type?: Prisma.StringFilter<"SentEmail"> | string
  createdAt?: Prisma.DateTimeFilter<"SentEmail"> | Date | string
  projectId?: Prisma.StringNullableFilter<"SentEmail"> | string | null
}

export type SentEmailCreateManyProjectInput = {
  id?: string
  type: string
  createdAt?: Date | string
}

export type SentEmailUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SentEmailUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SentEmailUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SentEmailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  createdAt?: boolean
  projectId?: boolean
  project?: boolean | Prisma.SentEmail$projectArgs<ExtArgs>
}, ExtArgs["result"]["sentEmail"]>



export type SentEmailSelectScalar = {
  id?: boolean
  type?: boolean
  createdAt?: boolean
  projectId?: boolean
}

export type SentEmailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "createdAt" | "projectId", ExtArgs["result"]["sentEmail"]>
export type SentEmailInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.SentEmail$projectArgs<ExtArgs>
}

export type $SentEmailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SentEmail"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    createdAt: Date
    projectId: string | null
  }, ExtArgs["result"]["sentEmail"]>
  composites: {}
}

export type SentEmailGetPayload<S extends boolean | null | undefined | SentEmailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SentEmailPayload, S>

export type SentEmailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SentEmailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SentEmailCountAggregateInputType | true
  }

export interface SentEmailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SentEmail'], meta: { name: 'SentEmail' } }
  /**
   * Find zero or one SentEmail that matches the filter.
   * @param {SentEmailFindUniqueArgs} args - Arguments to find a SentEmail
   * @example
   * // Get one SentEmail
   * const sentEmail = await prisma.sentEmail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SentEmailFindUniqueArgs>(args: Prisma.SelectSubset<T, SentEmailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SentEmail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SentEmailFindUniqueOrThrowArgs} args - Arguments to find a SentEmail
   * @example
   * // Get one SentEmail
   * const sentEmail = await prisma.sentEmail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SentEmailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SentEmailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SentEmail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailFindFirstArgs} args - Arguments to find a SentEmail
   * @example
   * // Get one SentEmail
   * const sentEmail = await prisma.sentEmail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SentEmailFindFirstArgs>(args?: Prisma.SelectSubset<T, SentEmailFindFirstArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SentEmail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailFindFirstOrThrowArgs} args - Arguments to find a SentEmail
   * @example
   * // Get one SentEmail
   * const sentEmail = await prisma.sentEmail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SentEmailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SentEmailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SentEmails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SentEmails
   * const sentEmails = await prisma.sentEmail.findMany()
   * 
   * // Get first 10 SentEmails
   * const sentEmails = await prisma.sentEmail.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sentEmailWithIdOnly = await prisma.sentEmail.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SentEmailFindManyArgs>(args?: Prisma.SelectSubset<T, SentEmailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SentEmail.
   * @param {SentEmailCreateArgs} args - Arguments to create a SentEmail.
   * @example
   * // Create one SentEmail
   * const SentEmail = await prisma.sentEmail.create({
   *   data: {
   *     // ... data to create a SentEmail
   *   }
   * })
   * 
   */
  create<T extends SentEmailCreateArgs>(args: Prisma.SelectSubset<T, SentEmailCreateArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SentEmails.
   * @param {SentEmailCreateManyArgs} args - Arguments to create many SentEmails.
   * @example
   * // Create many SentEmails
   * const sentEmail = await prisma.sentEmail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SentEmailCreateManyArgs>(args?: Prisma.SelectSubset<T, SentEmailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a SentEmail.
   * @param {SentEmailDeleteArgs} args - Arguments to delete one SentEmail.
   * @example
   * // Delete one SentEmail
   * const SentEmail = await prisma.sentEmail.delete({
   *   where: {
   *     // ... filter to delete one SentEmail
   *   }
   * })
   * 
   */
  delete<T extends SentEmailDeleteArgs>(args: Prisma.SelectSubset<T, SentEmailDeleteArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SentEmail.
   * @param {SentEmailUpdateArgs} args - Arguments to update one SentEmail.
   * @example
   * // Update one SentEmail
   * const sentEmail = await prisma.sentEmail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SentEmailUpdateArgs>(args: Prisma.SelectSubset<T, SentEmailUpdateArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SentEmails.
   * @param {SentEmailDeleteManyArgs} args - Arguments to filter SentEmails to delete.
   * @example
   * // Delete a few SentEmails
   * const { count } = await prisma.sentEmail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SentEmailDeleteManyArgs>(args?: Prisma.SelectSubset<T, SentEmailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SentEmails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SentEmails
   * const sentEmail = await prisma.sentEmail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SentEmailUpdateManyArgs>(args: Prisma.SelectSubset<T, SentEmailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one SentEmail.
   * @param {SentEmailUpsertArgs} args - Arguments to update or create a SentEmail.
   * @example
   * // Update or create a SentEmail
   * const sentEmail = await prisma.sentEmail.upsert({
   *   create: {
   *     // ... data to create a SentEmail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SentEmail we want to update
   *   }
   * })
   */
  upsert<T extends SentEmailUpsertArgs>(args: Prisma.SelectSubset<T, SentEmailUpsertArgs<ExtArgs>>): Prisma.Prisma__SentEmailClient<runtime.Types.Result.GetResult<Prisma.$SentEmailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SentEmails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailCountArgs} args - Arguments to filter SentEmails to count.
   * @example
   * // Count the number of SentEmails
   * const count = await prisma.sentEmail.count({
   *   where: {
   *     // ... the filter for the SentEmails we want to count
   *   }
   * })
  **/
  count<T extends SentEmailCountArgs>(
    args?: Prisma.Subset<T, SentEmailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SentEmailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SentEmail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SentEmailAggregateArgs>(args: Prisma.Subset<T, SentEmailAggregateArgs>): Prisma.PrismaPromise<GetSentEmailAggregateType<T>>

  /**
   * Group by SentEmail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SentEmailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SentEmailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SentEmailGroupByArgs['orderBy'] }
      : { orderBy?: SentEmailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SentEmailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSentEmailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SentEmail model
 */
readonly fields: SentEmailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SentEmail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SentEmailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.SentEmail$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SentEmail$projectArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SentEmail model
 */
export interface SentEmailFieldRefs {
  readonly id: Prisma.FieldRef<"SentEmail", 'String'>
  readonly type: Prisma.FieldRef<"SentEmail", 'String'>
  readonly createdAt: Prisma.FieldRef<"SentEmail", 'DateTime'>
  readonly projectId: Prisma.FieldRef<"SentEmail", 'String'>
}
    

// Custom InputTypes
/**
 * SentEmail findUnique
 */
export type SentEmailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter, which SentEmail to fetch.
   */
  where: Prisma.SentEmailWhereUniqueInput
}

/**
 * SentEmail findUniqueOrThrow
 */
export type SentEmailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter, which SentEmail to fetch.
   */
  where: Prisma.SentEmailWhereUniqueInput
}

/**
 * SentEmail findFirst
 */
export type SentEmailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter, which SentEmail to fetch.
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SentEmails to fetch.
   */
  orderBy?: Prisma.SentEmailOrderByWithRelationInput | Prisma.SentEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SentEmails.
   */
  cursor?: Prisma.SentEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SentEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SentEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SentEmails.
   */
  distinct?: Prisma.SentEmailScalarFieldEnum | Prisma.SentEmailScalarFieldEnum[]
}

/**
 * SentEmail findFirstOrThrow
 */
export type SentEmailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter, which SentEmail to fetch.
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SentEmails to fetch.
   */
  orderBy?: Prisma.SentEmailOrderByWithRelationInput | Prisma.SentEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SentEmails.
   */
  cursor?: Prisma.SentEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SentEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SentEmails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SentEmails.
   */
  distinct?: Prisma.SentEmailScalarFieldEnum | Prisma.SentEmailScalarFieldEnum[]
}

/**
 * SentEmail findMany
 */
export type SentEmailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter, which SentEmails to fetch.
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SentEmails to fetch.
   */
  orderBy?: Prisma.SentEmailOrderByWithRelationInput | Prisma.SentEmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SentEmails.
   */
  cursor?: Prisma.SentEmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SentEmails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SentEmails.
   */
  skip?: number
  distinct?: Prisma.SentEmailScalarFieldEnum | Prisma.SentEmailScalarFieldEnum[]
}

/**
 * SentEmail create
 */
export type SentEmailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * The data needed to create a SentEmail.
   */
  data: Prisma.XOR<Prisma.SentEmailCreateInput, Prisma.SentEmailUncheckedCreateInput>
}

/**
 * SentEmail createMany
 */
export type SentEmailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SentEmails.
   */
  data: Prisma.SentEmailCreateManyInput | Prisma.SentEmailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SentEmail update
 */
export type SentEmailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * The data needed to update a SentEmail.
   */
  data: Prisma.XOR<Prisma.SentEmailUpdateInput, Prisma.SentEmailUncheckedUpdateInput>
  /**
   * Choose, which SentEmail to update.
   */
  where: Prisma.SentEmailWhereUniqueInput
}

/**
 * SentEmail updateMany
 */
export type SentEmailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SentEmails.
   */
  data: Prisma.XOR<Prisma.SentEmailUpdateManyMutationInput, Prisma.SentEmailUncheckedUpdateManyInput>
  /**
   * Filter which SentEmails to update
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * Limit how many SentEmails to update.
   */
  limit?: number
}

/**
 * SentEmail upsert
 */
export type SentEmailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * The filter to search for the SentEmail to update in case it exists.
   */
  where: Prisma.SentEmailWhereUniqueInput
  /**
   * In case the SentEmail found by the `where` argument doesn't exist, create a new SentEmail with this data.
   */
  create: Prisma.XOR<Prisma.SentEmailCreateInput, Prisma.SentEmailUncheckedCreateInput>
  /**
   * In case the SentEmail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SentEmailUpdateInput, Prisma.SentEmailUncheckedUpdateInput>
}

/**
 * SentEmail delete
 */
export type SentEmailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
  /**
   * Filter which SentEmail to delete.
   */
  where: Prisma.SentEmailWhereUniqueInput
}

/**
 * SentEmail deleteMany
 */
export type SentEmailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SentEmails to delete
   */
  where?: Prisma.SentEmailWhereInput
  /**
   * Limit how many SentEmails to delete.
   */
  limit?: number
}

/**
 * SentEmail.project
 */
export type SentEmail$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
}

/**
 * SentEmail without action
 */
export type SentEmailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SentEmail
   */
  select?: Prisma.SentEmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SentEmail
   */
  omit?: Prisma.SentEmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SentEmailInclude<ExtArgs> | null
}
