export const googleAdsEnv = {
  GOOGLE_ADS_CLIENT_ID: process.env.GOOGLE_ADS_CLIENT_ID || "",
  GOOGLE_ADS_CLIENT_SECRET: process.env.GOOGLE_ADS_CLIENT_SECRET || "",
  GOOGLE_ADS_DEVELOPER_TOKEN: process.env.GOOGLE_ADS_DEVELOPER_TOKEN || "",
  GOOGLE_DATA_PARTNER_ACCOUNT_ID:
    process.env.GOOGLE_DATA_PARTNER_ACCOUNT_ID || "",
  GOOGLE_DATA_PARTNER_REFRESH_TOKEN:
    process.env.GOOGLE_DATA_PARTNER_REFRESH_TOKEN || "",
};
