export const REFERRALS_EMBED_EARNINGS_LIMIT = 8;
export const CUSTOMER_PAGE_EVENTS_LIMIT = 8;
export const MEGA_WORKSPACE_LINKS_LIMIT = 1_000_000;
export const MIN_PAYOUT_AMOUNT_FOR_REMINDERS = 10_00;
